---
title: "Analyze Drug Response"
author: "Jessica Scarborough"
date: "12/10/2021"
output: html_document
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r load_packages}

library(knitr)
library(here)
library(tidyverse)

```


# Load Data


```{r load_data}

tidy_data <- readRDS(here("Data", "del_dr_data.rds"))

```


# Run Statistics


```{r run_stats, message=FALSE, warning=FALSE}

compare_wilcox <- function(data, drug, del_label){
  filtered_data <- data %>%
    filter(DRUG_NAME == drug) %>%
    mutate(label = as.numeric(as.factor(UQ(sym(del_label))))) # 1 = No; 2 = Yes
  if(nrow(filtered_data) > 1){
    if(length(unique(filtered_data$label)) == 2){
      result <- wilcox.test(IC50~label, data = filtered_data)
      return(result)
    }
  }
  return(NA)
}

drug_vec <- c()
result_chr7_vec <- c()
result_chr7q_vec <- c()

for(drug in unique(tidy_data$DRUG_NAME)) {
  
  result_chr7_wilcox <- compare_wilcox(tidy_data, drug, "chr7_del")
  if(is.na(result_chr7_wilcox)==FALSE){
    result_chr7_wilcox <- result_chr7_wilcox$p.value
  }
  result_chr7q_wilcox <- compare_wilcox(tidy_data, drug, "chr7q_del")
    if(is.na(result_chr7q_wilcox)==FALSE){
    result_chr7q_wilcox <- result_chr7q_wilcox$p.value
  }
  
  drug_vec <- c(drug_vec, drug)
  
  result_chr7_vec <- c(result_chr7_vec, result_chr7_wilcox)
  result_chr7q_vec <- c(result_chr7q_vec, result_chr7q_wilcox)
}

result_df <- data.frame(drug = drug_vec, wilcox_p_chr7 = result_chr7_vec,
                        wilcox_p_chr7q = result_chr7q_vec)

result_df <- result_df %>%
  mutate(wilcox_p_bonf_chr7 = wilcox_p_chr7 * nrow(result_df),
         wilcox_p_bonf_chr7q = wilcox_p_chr7q * nrow(result_df),
         wilcox_p_bonf_chr7 = ifelse(wilcox_p_bonf_chr7 > 1, 1, wilcox_p_bonf_chr7), # anything over 1 becomes 1
         wilcox_p_bonf_chr7q = ifelse(wilcox_p_bonf_chr7q > 1, 1, wilcox_p_bonf_chr7q)) # anything over 1 becomes 1

result_chr7_df <- result_df %>%
  select(drug, p_value = wilcox_p_chr7, p_corr = wilcox_p_bonf_chr7)

result_chr7q_df <- result_df %>%
  select(drug, p_value = wilcox_p_chr7q, p_corr = wilcox_p_bonf_chr7q)

write.csv(result_df, file = here("Results", "wilcox_compare_results.csv"))

```


# Plot Waterfalls


```{r plot_waterfall, message=FALSE}

plot_waterfall <- function(data, drug, color_label, wilcox_results){
  # filter by drug, order df by IC50 to create order in waterfall plot
  filtered_data <- data %>%
    filter(DRUG_NAME == drug) %>%
    arrange(IC50) %>%
    mutate(order_label = factor(IC50, levels = unique(IC50)))
  p_result <- round(wilcox_results[wilcox_results$drug == drug, "p_value"], 4)
  p_corr_result <- round(wilcox_results[wilcox_results$drug == drug, "p_corr"], 4)
  drug_waterfall <- ggplot(filtered_data, aes(x = order_label, y = IC50, 
                                              color = UQ(sym(color_label)), 
                                              fill = UQ(sym(color_label)))) + 
    geom_bar(stat = "identity") + 
    labs(x = "Cell Line", y = "log2(IC50)") + 
    scale_color_manual(values=c("navajowhite3", "darkseagreen4")) +
    scale_fill_manual(values=c("navajowhite3", "darkseagreen4")) +
    annotate("text", x = 100, y = 6, label = paste("p-value:", p_result)) +
    annotate("text", x = 100, y = 5, label = paste("corrected p-value:", p_corr_result)) +
    theme_classic() +
    theme(axis.text.x=element_blank(),
        axis.ticks.x=element_blank())
  ggsave(here("Plots", "Waterfall", color_label, paste0("waterfall_", drug, ".png")), plot = drug_waterfall)
}

# plot_waterfall(tidy_data, "Cisplatin", color_label = "chr7q_del", result_chr7q_df)


for(drug in unique(tidy_data$DRUG_NAME)) {
  plot_waterfall(tidy_data, drug, color_label = "chr7_del", result_chr7_df)
}

for(drug in unique(tidy_data$DRUG_NAME)) {
  plot_waterfall(tidy_data, drug, color_label = "chr7q_del", result_chr7q_df)
}

```

# Plot Violins


```{r plot_violin, message=FALSE}

plot_violins <- function(data, drug, deletion_label, wilcox_results){
  filtered_drug_data <- data %>%
    filter(DRUG_NAME == drug)
  filtered_drug_del_data <- data %>%
    filter(DRUG_NAME == drug) %>%
    filter(UQ(sym(deletion_label)) == "Yes")
  p_result <- round(wilcox_results[wilcox_results$drug == drug, "p_value"], 4)
  p_corr_result <- round(wilcox_results[wilcox_results$drug == drug, "p_corr"], 4)
  violin_plot <- ggplot(filtered_drug_data) + 
    geom_violin(aes(x = drug, y = IC50, fill = "navajowhite3"), 
                scale = "count", trim = FALSE, draw_quantiles = c(0.25, 0.5, 0.75)) + 
    geom_violin(data = filtered_drug_del_data, 
                aes(x = drug, y = IC50, fill = "darkseagreen4"), 
                trim = FALSE, width = 0.1, draw_quantiles = c(0.25, 0.5, 0.75)) + 
    scale_fill_identity(name = "Cell Line Groups",
                        breaks = c("navajowhite3", "darkseagreen4"),
                        labels = c("All cell lines", paste(deletion_label, "cell lines")),
                        guide = "legend") +
    coord_flip() + 
    labs(x = drug, y = "log2(IC50)") +
    annotate("text", x = 0.5, y = 1, label = paste("p-value:", p_result)) +
    annotate("text", x = 0.45, y = 1, label = paste("corrected p-value:", p_corr_result)) +
    theme_classic() +
    theme(axis.text.y = element_blank())
  ggsave(here("Plots", "Violin", deletion_label, paste0("violin_", drug, ".png")))

}


for (drug in unique(tidy_data$DRUG_NAME)){
  filtered_data_test <- tidy_data %>% 
    filter(DRUG_NAME == drug & chr7_del == "Yes")
  if(nrow(filtered_data_test) > 1){
  plot_violins(tidy_data, drug, "chr7_del", wilcox_results = result_chr7_df)
  }
}

for (drug in unique(tidy_data$DRUG_NAME)){
  filtered_data_test <- tidy_data %>% 
    filter(DRUG_NAME == drug & chr7q_del == "Yes")
  if(nrow(filtered_data_test) > 1){
    plot_violins(tidy_data, drug, "chr7q_del", wilcox_results = result_chr7q_df)
  }
}

```

